### ISSUE TITLE
Valid location values

### ISSUE THREAD

**Issue by heebtob** [jonathandreyer/node-red-contrib-swissforecast#1]
I tried to use the node in node-red but it doesn't work.
I tried it with postal code or with city name.
What kind of location value do I have to fill in?

**Comment by jonathandreyer** [comment]
Hello, it is a abbreviation of city. You can find this abbreviation [there](https://www.meteoswiss.admin.ch/home/measurement-values.html).

**Comment by jdpcmt** [comment]
Hi,
The link above is not showing the valid abbreviations anymore. The page seems to be now located at
https://www.meteoswiss.admin.ch/home/measurement-and-forecasting-systems/land-based-stations/data-availability.html

**Comment by jonathandreyer** [comment]
Hi @jdpcmt, you have right. I have made a mistake in my previous message with the formatting, but the link is correct (now it is fixed). It is also more simpler to see abbreviation when it is in [table](https://www.meteoswiss.admin.ch/home/measurement-values.html?table=true) mode.
